---
# first time login to Ubuntu creds
ansible_ssh_common_args: -o StrictHostKeyChecking=no -o PreferredAuthentications=password
ansible_ssh_user: ubuntu
ansible_ssh_password: dummy-password
ubuntu_default_password: ubuntu
