---

- hosts: all
  become: true
  gather_facts: false
  roles:
    - role: passwordless

- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: configure
    - role: apt_upgrade
    - role: mounts
