---

# Handle the enforced password change at first login
- hosts: orker3
  become: no
  gather_facts: no
  roles:
    - role: passwordless

# - hosts: all
#   gather_facts: yes
#   become: yes
#   roles:
#     - role: configure
#     - role: apt_upgrade
#     - role: mounts
