---

# Handle the enforced password change at first login
- hosts: all
  gather_facts: no
  become: no
  roles:
    - role: first_time_login
    - role: users
      become: yes

# Create new users, disable the default user, configure
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: configure
    - role: apt_upgrade
