---

- name: "Try first login and change the password if required"
  when: perform_initial_password_change == true
  block:

  - name: "Try changing the default password"
    delegate_to: localhost
    # hosts with passwords already changed will raise an error
    ignore_unreachable: true
    ignore_errors: true
    expect:
      command: >
        sshpass -p {{ ubuntu_default_password }}
        ssh {{ ansible_ssh_common_args }}
        {{ ansible_ssh_user }}@{{ ansible_host }}
      timeout: 10
      responses:
        "Current password: ": "{{ ubuntu_default_password }}"
        "New password: ": "{{ ansible_ssh_password }}"
        "Retype new password: ": "{{ ansible_ssh_password }}"
    register: password_change
    changed_when:
      "'passwd: password updated successfully' in password_change.stdout"

  - name: PING
    action: ping
