---
- name: Mount drives and set up NFS
  when: mounts|length > 0
  block:

  - name: Mount drives
    ansible.builtin.include_tasks: mount.yaml
    when: item.host|string == inventory_hostname
    with_items: "{{ mounts }}"
    loop_control:
      label: "{{ item.label }} mount at {{ item.mountpoint }}"

  - name: Set up NFS
    ansible.builtin.include_tasks: nfs.yaml
    when: inventory_hostname in mounts | map(attribute='host') | list

  - name: Add the nfs-common package
    ansible.builtin.apt:
      name: nfs-common
      state: present
