---
# add nfs and nfsd to make NFS server pods work
# not sure if this works on boot
- name: Enable nfs
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/nfs.conf
    line: nfs
    create: true
    mode: 0644
  notify: reboot

- name: Enable nfsd
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/nfsd.conf
    line: nfsd
    create: true
    mode: 0644
  notify: reboot

# this is a workaround for loading kernel modules
- name: Add the nfs module
  community.general.modprobe:
    name: nfs
    state: present

- name: Add the nfsd module
  community.general.modprobe:
    name: nfsd
    state: present
