---

# hostname
- name: Set hostname
  ansible.builtin.hostname: name="{{ hostname }}"
  notify: reboot

# memsplit
- name: Check memsplit
  ansible.builtin.command: |
    awk /^gpu_mem={{ memsplit }}$/ /boot/firmware/config.txt
  register: memsplit_set
  check_mode: false
  ignore_errors: true
  changed_when: false

- name: Set memsplit
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^gpu_mem='
    line: 'gpu_mem={{ memsplit }}'
  when: memsplit_set.rc != 0
  notify: reboot

# wifi_enabled
- name: Set wifi status - disable
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=disable-wifi'
    line: 'dtoverlay=disable-wifi'
    state: present
  when: not wifi_enabled
  notify: reboot

- name: Set wifi status - enable
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=disable-wifi'
    line: 'dtoverlay=disable-wifi'
    state: absent
  when: wifi_enabled
  notify: reboot

# bt_enabled
- name: Set bt status - disable
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=disable-bt'
    line: 'dtoverlay=disable-bt'
    state: present
  when: not bt_enabled
  notify: reboot

- name: Set bt status - enable
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=disable-bt'
    line: 'dtoverlay=disable-bt'
    state: absent
  when: bt_enabled
  notify: reboot


# fan_control
- name: Enable GPIO fan control
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=gpio-fan'
    line: 'dtoverlay=gpio-fan,gpiopin=3,temp=70000'
    state: present
  when: fan_control == "gpio"
  notify: reboot
    
- name: POE fan control
  ansible.builtin.blockinfile:
    path: /boot/firmware/config.txt
    marker: "# {mark} POE fan control (ansible managed)"
    block: |
      dtparam=poe_fan_temp0=55000
      dtparam=poe_fan_temp0_hyst=5000
      dtparam=poe_fan_temp1=60000
      dtparam=poe_fan_temp1_hyst=5000
      dtparam=poe_fan_temp2=65000
      dtparam=poe_fan_temp2_hyst=5000
      dtparam=poe_fan_temp3=75000
      dtparam=poe_fan_temp3_hyst=5000
    state: "{{ 'present' if fan_control == 'poe' else 'absent' }}"
  notify: reboot

- name: Disable GPIO fan control
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtoverlay=gpio-fan'
    state: absent
  when: fan_control != "gpio"
  notify: reboot

# timezone
- name: Check timezone
  ansible.builtin.command: grep "{{ timezone }}" /etc/timezone
  register: timezone_set
  failed_when: false
  changed_when: false

- name: Set timezone
  ansible.builtin.command: timedatectl set-timezone {{ timezone }}
  when: timezone_set.rc != 0
  notify: reboot
