---
- name: Use default Ubuntu credentials
  set_fact:
    ansible_ssh_user: "{{ ubuntu_default_user }}"
    ansible_ssh_password: "{{ ubuntu_default_password }}"
    ansible_ssh_common_args: "{{ ssh_password_auth_args }}"

- name: Try changing the default password
  delegate_to: localhost
  ignore_unreachable: true
  ignore_errors: true
  ansible.builtin.expect:
    command: >
      sshpass -p {{ ansible_ssh_password }}
      ssh {{ ansible_ssh_common_args }}
      {{ ansible_ssh_user }}@{{ ansible_host }}
    responses:
      "Current password: ": "{{ ansible_ssh_password }}"
      "New password: ": "{{ ubuntu_temp_password }}"
      "Retype new password: ": "{{ ubuntu_temp_password }}"
    timeout: 10
