---
# for some reason ansible's "stat" function does not find the keys
# key_stat.results[i].stdout will be "0" if there is no key, otherwise "1"
- name: Check if the ssh keys already exist locally
  delegate_to: localhost
  become: false
  changed_when: false
  ansible.builtin.shell: |
    set -o pipefail && ls -l {{ item.key_path }} 2>/dev/null | wc -l
  args:
    executable: /bin/bash
  with_items: "{{ users }}"
  register: key_stat
  loop_control:
    label: "{{ item.key_path }}"

- name: Generate missing ssh keys
  delegate_to: localhost
  become: false
  ansible.builtin.command: |
    ssh-keygen -q -t ed25519 -f {{ item.item.key_path }} -C "" -N ""
  args:
    creates: "{{ item.item.key_path }}"
  with_items: "{{ key_stat.results }}"
  when: item.stdout == "0"
  loop_control:
    label: "{{ item.item.key_path }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: present
    create_home: true
    shell: /bin/bash
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Add users to sudoers
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.username }}"
    content: "{{ item.username }}  ALL=(ALL)  NOPASSWD: ALL"
    mode: preserve
  with_items: "{{ users }}"
  when: item.sudoer
  loop_control:
    label: "{{ item.username }}"

- name: Copy public key to the hosts
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', '{{ item.key_path }}.pub') }}"
    state: present
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.key_path }}"

- name: Disable password for the default user
  ansible.builtin.user:
    name: ubuntu
    password_lock: true

- name: Ensure ansible user is used from now on
  ansible.builtin.set_fact:
    ansible_ssh_user: "{{ ansible_default_user }}"
    ansible_ssh_common_args: "{{ ssh_publickey_auth_args }}"
