---

- name: Check connection
  ansible.builtin.wait_for_connection:
    timeout: 30
  ignore_errors: true
  register: connection_status

- name: Ubuntu first time login password change
  ansible.builtin.include_tasks: change_default_password.yaml
  when: |
    connection_status.failed and
    'Permission denied' in connection_status.msg

- name: Use temporary Ubuntu credentials
  ansible.builtin.set_fact:
    ansible_ssh_user: "{{ ubuntu_default_user }}"
    ansible_ssh_password: "{{ ubuntu_temp_password }}"
    ansible_ssh_common_args: "{{ ssh_password_auth_args }}"
  when: |
    connection_status.failed and
    'Permission denied' in connection_status.msg

- name: Create users with passwordless access
  ansible.builtin.include_tasks: create_users.yaml
