---

- name: Check the connection
  ansible.builtin.ping:
  ignore_unreachable: true
  ignore_errors: true
  register: connection_status

- name: Ubuntu first time login password change
  when: "'ping' not in connection_status"
  become: false
  include: change_default_password.yaml

- name: Use temporary Ubuntu credentials
  when: "'ping' not in connection_status"
  set_fact:
    ansible_ssh_user: "{{ ubuntu_default_user }}"
    ansible_ssh_password: "{{ ubuntu_temp_password }}"
    ansible_ssh_common_args: "{{ ssh_password_auth_args }}"

- name: Create users with passwordless access
  include: create_users.yaml
