---
name: Lint

on: # yamllint disable-line
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**"
      - "**.yaml"
      - "**.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Run yamllint
        run: make lint-yaml

      - name: Run ansible-lint
        run: make lint-ansible
